westerndevs/western-devs-website

- _config-dev.yml
- _config.yml
To run locally:
`jekyll serve --config _config.yml,_config-dev.yml`
> Fix social links

- Gemfile.lock
- _layouts/bio.html
- _posts/2015-06-23-repository-nightmares.markdown
> Kb disallow comments on bios

- _data/authors.yml
Hmm, does D'arcy come before 'da' or after 'dz'
> Ordered authors alphabetical by first name

- _config.yml
- _data/navigation.yml
- _data/podcasts.yml
- _includes/_author-bio.html
- whatwevesaid/index.slim
> Add podcasts page; other tweaks

- _data/authors.yml
- _includes/_author-bio.html
- _plugins/to_gravatar.rb
> Use gravatar where possible

- _data/podcasts.yml
- _includes/_podcast.html
- _layouts/podcast-index.html
- _plugins/render_podcast.rb
Also added a Download MP3 button to the podcast page
> Update to use Azure CDN

- _drafts/2015-07-08-microservices.markdown
- about/index.slim
Ignore the draft post on microservices. It's a work in progress.
> Update who we are

- _includes/_author-bio.html
> Fix issue #70

- _layouts/home.html
- _sass/page.scss
Fixes #37
Added date and link to the author after the post title
> Added date and author for each post on home

- _azure/deploy.ps1
- _azure/wddocker.json
Added ability to delete RG when done
doesn't prompt for azure subscription if you only have one
removed some unnecessary stuff at the start
auto-converts inputs to lowercase where necessary
GUI selector for azure sub if you have more than one
> Azure PowerShell updates

- _posts/2015-09-08-westerndevs-learn-about-docker-part-2.markdown
> Initial revision

- _config.yml
- themes/westerndevs/layout/_partial/article.ejs
- themes/westerndevs/layout/layout.ejs
- themes/westerndevs/layout/podcast.ejs
Added comments section to blog posts and podcasts
> Added disqus comments

- themes/westerndevs/layout/_widget/home_page/latest_podcast.ejs
> Latest podcast widget

- themes/westerndevs/layout/whatwevedone.ejs
Someone just told me I'm not supposed to code after having a drink...they clearly haven't heard of the Ballmer peak.
Closes #113
> Author names like a boss

- source/_data/speaking.yml
- themes/westerndevs/layout/_partial/header.ejs
- themes/westerndevs/layout/_widget/home_page/speaking.ejs
- themes/westerndevs/layout/speaking.ejs
Fixed #116 
Also addresses an issue with date sorting (it wasn't sorting).
> Widget for speaking engagements on home page

- package.json
- source/404.md
- themes/westerndevs/layout/404.ejs
> updated the 404 page to keep Kyle from complaining about it

- package.json
- themes/westerndevs/layout/404.ejs
fixed 404 image url to work in all locations on the site
> Fixed 404 image URL

- source/about/index.md
removed dashes from broken link
> Fix broken link to us

- _config.yml
- package.json
Apparently good for SEO.
Closes issue #148
> Added a sitemap

- themes/westerndevs/source/css/style.styl
It sounds crazy but apparently this is what people want
> Display large images even on a phone

- source/_posts/2016-07-18-keeping-your-edge.md
Because I'm rusty, I would like someone to verify I'm doing this right.
> Cross Post Verification

- source/_posts/2016-09-23-Hour-of-Code-Challenge.md
> Hour of code challenge post

- themes/westerndevs/layout/author.ejs
> Display list of blog posts on author page

- source/_posts/2017-03-08-Synchronize-GitHub-Repository-With-VSTS.md
don't accept yet, want to wait to merge this since we just had 2 posts today/yesterday
> Sync GitHub and VSTS post

- themes/westerndevs/layout/_partial/post/title.ejs
- themes/westerndevs/source/css/style.styl
Here's what it looks like on desktop:
Still needs some work for mobile:
> Add post date

- .travis.yml
This includes:
+ Using Node 8.x to run the build
+ Runs build ONLY on `master`
> Updating build script.

- source/_authors/tyler_doerksen.yml
- source/_data/authors.yml
- source/bios/tyler_doerksen.md
I tried to model the data off of other members.
I could not get it running on my local machine, but I expect that was a hexo server problem.
> Adding Tyler Doerksen

- themes/westerndevs/layout/_partial/head.ejs
added conditional to post head to add canonical tag if originalurl is set
> Canonical Tag
